### ISSUE TITLE
Very useful work.

### ISSUE THREAD

**Issue by jiangchaokang** [kazuto1011/r2dm#1]
Is there very little work involved in LiDAR point cloud generation? Because I saw that your paper only compared one method, LiDARGen [5].

**Comment by kazuto1011** [comment]
Thank you for your interest in our work. Not so many but there are some related studies as addressed in our paper, and we employed some code/sample-available methods as baselines depending on the datasets; overall, it's not only LiDARGen. We will conduct a comprehensive and consistent investigation in future work.
