### ISSUE TITLE
Problem upsampling lidar

### ISSUE THREAD

**Issue by TristanCot** [kazuto1011/r2dm#10]
Hello, I can get it to work by using completion_demo, but I can't get what I want and I need your help.

I'm trying to upsample a point cloud that is at 32 beams.
In the first case, I put the point cloud in its 64-beam version, I apply a mask that removes one beam out of 2, and we can see the completion that takes place and therefore the upsampling.
![image](https://github.com/user-attachments/assets/dcd747a5-639d-4ca4-9c30-22fbc03b4cb0)

But when I input a 32 beams point cloud directly, completion does not take place and so I have no upsampling, as can be seen:
![image](https://github.com/user-attachments/assets/7c61d4c4-50c4-47e8-853c-6c3a8da5f7f5)

Do you have any idea how I could go about upsampling directly from a 32-beam point cloud?

**Comment by kazuto1011** [comment]
Have you made the mask that indicates whether to fill? If not, please define the mask, such as `(depth > 0).float()`, and feed it into the repaint function; otherwise, the function will leave all the pixels as is.
https://github.com/kazuto1011/r2dm/blob/ad66e71e86051d0341e096c60ece30a7de6c5b3f/completion_demo.py#L94

**Comment by TristanCot** [comment]
> Have you made the mask that indicates whether to fill? If not, please define the mask, such as `(depth > 0).float()`, and feed it into the repaint function; otherwise, the function will leave all the pixels as is.
> 
> https://github.com/kazuto1011/r2dm/blob/ad66e71e86051d0341e096c60ece30a7de6c5b3f/completion_demo.py#L94

Thank you very much, that's what I was missing, thank you for your work!
