### ISSUE TITLE
The generation of range map and reflectance map

### ISSUE THREAD

**Issue by Huang-yihao** [kazuto1011/r2dm#2]
Could you please give the way of generating range map and reflectance map from Lidar point clouds?
Also, how to generate Lidar point clouds with range map and reflectance map?
Thank you!

**Comment by kazuto1011** [comment]
The conversion parts can also be found in our previous work; [point-to-image](https://github.com/kazuto1011/dusty-gan-v2/blob/main/gans/datasets/kitti.py#L317-L370) and [image-to-point](https://github.com/kazuto1011/dusty-gan-v2/blob/main/gans/coords.py#L178-L185).
Our code release is still in preparation.
