### ISSUE TITLE
kitti-360 data download

### ISSUE THREAD

**Issue by Summer608** [kazuto1011/r2dm#3]
Hello! How did you download the kitti-360 data set in the article? I cannot download data using ‘download_3d_velodyne.sh‘ provided by the official website.

**Comment by kazuto1011** [comment]
I did it with the official script. I downloaded it again just to be sure and tried running it, and it seems to work fine.
`bash download_3d_velodyne.sh`

**Comment by kazuto1011** [comment]
Let me close the issue since it is related to the dataset side.
