### ISSUE TITLE
Can this work generate a continuous signal of lidar points, or generate different lidar points according to given viewports?

### ISSUE THREAD

**Issue by Tumiz** [kazuto1011/r2dm#4]

**Comment by kazuto1011** [comment]
This model was not designed to generate continuous signals (4D points?) but viewpoint-wise point clouds.

**Comment by Tumiz** [comment]
Yes, I mean 4D points like what real lidar sensors generate on autonomous vehicles. If this model is not designed to do this, how to use the model in a simulation task?

**Comment by kazuto1011** [comment]
In this work, we focused on building data priors as a basis for future applications and demonstrated one of them: sparse-to-dense completion (1 frame). For your case, I think it needs to take one step further, such as manipulating latent variables to produce temporally-consistent outputs.

**Comment by Tumiz** [comment]
Thank you
